/* ------------------------------------------------------------------------
   slots.js — GENERATED by build.js. Do not edit by hand.

   The photographs placed into <image-slot> regions in the design, plus the
   crop the designer chose for each one. See js/image-slot.js for what s/x/y
   mean and how they are applied.
------------------------------------------------------------------------ */
window.IMAGE_SLOTS = {
  "portico-hero": { src: "assets/portico-hero.webp", s: 1.383476, x: 67.3147, y: 0.9938 },
  "atrium-hero": { src: "assets/atrium-hero.webp", s: 1, x: 0, y: 20.7217 },
  "center-hero": { src: "assets/center-hero.webp", s: 1, x: 0, y: -18.8357 },
  "mrd-t3": { src: "assets/mrd-t3.webp", s: 1, x: 0, y: 0 },
  "mrd-t2": { src: "assets/mrd-t2.webp", s: 1, x: 0, y: 0 },
  "mrd-t1": { src: "assets/mrd-t1.webp", s: 1, x: 0, y: 0 },
  "mrd-hero": { src: "assets/mrd-hero.webp", s: 1, x: 0, y: -1.7258 },
  "cst-mark": { src: "assets/cst-mark.webp", s: 1, x: 0, y: 0 },
  "vt-hero": { src: "assets/vt-hero.webp", s: 1, x: 0, y: 0 },
  "qd-hero": { src: "assets/qd-hero.webp", s: 1, x: 0, y: 5.8889 },
  "3h-banner": { src: "assets/3h-banner.webp", s: 1, x: 0, y: -23.6643 },
  "bed-hero": { src: "assets/bed-hero.webp", s: 1, x: 0, y: 23.134 },
  "4f2-panel": { src: "assets/4f2-panel.webp", s: 1, x: -77.5399, y: 0 }
};
