#!/usr/bin/env node
/* ---------------------------------------------------------------------------
   build.js — regenerate js/templates.js from the files in layouts/.

     node build.js

   layouts/*.html are the source of truth and are meant to be edited directly.
   They are bundled into a single js/templates.js for one reason: opening
   index.html straight off the disk uses the file:// protocol, where fetch()
   is blocked, so the page could not load its own partials. Bundling them as a
   script means index.html works by double-click, with no server and no
   toolchain.

   Run this after editing anything in layouts/. There are no dependencies.
--------------------------------------------------------------------------- */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const LAYOUTS = path.join(ROOT, 'layouts');
const OUT = path.join(ROOT, 'js', 'templates.js');

const HEADER = `/* ------------------------------------------------------------------------
   templates.js — GENERATED by build.js. Do not edit by hand.

   Edit the partials in layouts/ instead, then run \`node build.js\`.
------------------------------------------------------------------------ */
`;

function jsString(s) {
  // Template literals keep the markup readable in the bundle; only backticks,
  // backslashes and ${ need escaping, none of which appear in the source.
  return '`' + s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${') + '`';
}

function main() {
  const files = fs.readdirSync(LAYOUTS)
    .filter((f) => f.endsWith('.html'))
    .sort();

  const entries = files.map((f) => {
    const id = path.basename(f, '.html');
    const body = fs.readFileSync(path.join(LAYOUTS, f), 'utf8').replace(/\s+$/, '');
    return '  ' + JSON.stringify(id) + ': ' + jsString(body);
  });

  fs.writeFileSync(OUT, HEADER + 'window.TEMPLATES = {\n' + entries.join(',\n\n') + '\n};\n');

  const bytes = fs.statSync(OUT).size;
  console.log(
    `templates.js  ${files.length} partials  ${(bytes / 1024).toFixed(0)} KB`
  );
  for (const f of files) console.log('  ' + f);
}

main();
